%edades de los pacientes

edad(adolfoleoncorreasilva,52).
edad(alejandroalzategarces,58).
edad(alfredotobontobon,57).
edad(alvarodejesusbocanumenthpuerta,29).
edad(alvarodejesussaldarriagavasquez,16).
edad(alvaroivanberdugolopez,42).
edad(angelgabrielarrublaortiz,26).
edad(armidbenjaminmunozramirez,25).
edad(arturotabaresmora,56).
edad(augustoosornogil1,58).
edad(beatrizelenaosoriolaverde,27).
edad(beatrizelenapuertabolivar,85).
edad(bernardoposadavera,42).
edad(carlosalbertovillegaslopera,7).
edad(carlosalbertozarateyepez,19).
edad(carlosaugustogiraldo,51).
edad(carlosmariomontoyaserna,26).
edad(cesaroswaldopalaciomartinez,7).
edad(octaviodiazperez,68).
edad(fabioalexanderflorezgarcia,25).
edad(gabrieljaimejimenezgomez,48).
edad(gerardoemilioduquegutierrez,13).
edad(germanantonioloteroupegui,33).
edad(gloriaamparoalzateagudelo,26).
edad(gloriaelenasanclementezea,35).
edad(gonzalolopezgaviria,11).
edad(gustavohernanrodriguezvallejo,32).
edad(hectordamianmosquerabenitez,66).
edad(hectordariobermudezsaldarriaga,65).
edad(hectorivangonzalezcastaño,28).
edad(hectormanuelpineda,28).
edad(hermancorrearamirez,36).
edad(hernandariohurtadoperez,83).
edad(horacioaugustomorenocorrea1,33).
edad(jaimelopeztobon,22).
edad(javierignacioaguilargomez,35).
edad(javierignaciomolinacano,28).
edad(jhonyalbertosaenzhurtado,15).
edad(johnjairoduquegarcia,13).
edad(jorgeleonruizruiz,65).
edad(jorgeuribebotero,8).
edad(josedidierzapatasuarez,59).
edad(juliocesarrodasmonsalve1,70).
edad(juliocesarrodriguezmonsalve,59).
edad(lidapatriciagiraldomorales,56).
edad(lillianeugeniagomezalvarez,70).
edad(luisalfonsoescobartrujillo,18).
edad(luisanibalsepulvedavillada,41).
edad(luisfernandocastrohernandez,84).
edad(luisguillermovelezosorio,48).
edad(luisoliveriocardenasmoreno,55).
edad(mariaisabellopezgaviria,56).
edad(mariavictoriaariasgomez,15).
edad(oscardariogomezgiraldo,32).
edad(oscardariomurillogonzalez,4).
edad(sixtonaranjomarin,15).
edad(williamdejramirezvasquez,15).
