%lista de hospitales en los cuales los pacientes se encuentran

hospital(adolfoleoncorreasilva,hospitalgeneraldelacdmx).
hospital(alejandroalzategarces,hospitalgeneraldevalladolid).
hospital(alfredotobontobon,hospitalgeneraldelacdmx).
hospital(alvarodejesusbocanumenthpuerta,hospitalgeneraldelacdmx).
hospital(alvarodejesussaldarriagavasquez,hospitalgeneraldevalladolid).
hospital(alvaroivanberdugolopez,hospitalgeneraldelacdmx).
hospital(angelgabrielarrublaortiz,hospitalgeneraldechampoton).
hospital(armidbenjaminmunozramirez,hospitalgeneraldelacdmx).
hospital(arturotabaresmora,hospitalgeneraldelacdmx).
hospital(augustoosornogil,hospitalgeneraldelacdmx).
hospital(beatrizelenaosoriolaverde,hospitalgeneraldechampoton).
hospital(beatrizelenapuertabolivar,hospitalgeneraldechampoton).
hospital(bernardoposadavera,hospitalgeneraldelacdmx).
hospital(carlosalbertovillegaslopera,hospitalgeneraldecancun).
hospital(carlosalbertozarateyepez,imss).
hospital(carlosaugustogiraldo,imss).
hospital(carlosmariomontoyaserna,hospitalgeneraldechampoton).
hospital(cesaroswaldopalaciomartinez,hospitalgeneraldecancun).
hospital(octaviodiazperez,hospitalgeneraldevalladolid).
hospital(fabioalexanderflorezgarcia,hospitalgeneraldevalladolid).
hospital(gabrieljaimejimenezgomez,institutonacionaldeenfermedadesrespiratorias).
hospital(gerardoemilioduquegutierrez,imss).
hospital(germanantonioloteroupegui,institutonacionaldeenfermedadesrespiratorias).
hospital(gloriaamparoalzateagudelo,hospitalgeneraldevalladolid).
hospital(gloriaelenasanclementezea,hospitalgeneraldelacdmx).
hospital(gonzalolopezgaviria,imss).
hospital(gustavohernanrodriguezvallejo,hospitalgeneraldevalladolid).
hospital(hectordamianmosquerabenitez,hospitalgeneraldevalladolid).
hospital(hectordariobermudezsaldarriaga,hospitalgeneraldechampoton).
hospital(hectorivangonzalezcastaño,hospitalgeneraldechampoton).
hospital(hectormanuelpineda,hospitalgeneraldechampoton).
hospital(hermancorrearamirez,hospitalgeneraldelacdmx).
hospital(hernandariohurtadoperez,imss).
hospital(horacioaugustomorenocorreal,imss).
hospital(jaimelopeztobon,hospitalgeneraldevalladolid).
hospital(javierignacioaguilargomez,hospitalgeneraldecancun).
hospital(javierignaciomolinacano,hospitalgeneraldevalladolid).
hospital(jhonyalbertosaenzhurtado,imss).
hospital(johnjairoduquegarcia,imss).
hospital(jorgeleonruizruiz,hospitalgeneraldecancun).
hospital(jorgeuribebotero,hospitalgeneraldechampoton).
hospital(josedidierzapatasuarez,hospitalgeneraldevalladolid).
hospital(juliocesarrodasmonsalvex,imss).
hospital(juliocesarrodriguezmonsalve,hospitalgeneraldecancun).
hospital(lidapatriciagiraldomorales,hospitalgeneraldelacdmx).
hospital(lillianeugeniagomezalvarez,hospitalgeneraldelacdmx).
hospital(luisalfonsoescobartrujillo,imss).
hospital(luisanibalsepulvedavillada,imss).
hospital(luisfernandocastrohernandez,hospitalgeneraldechampoton).
hospital(luisguillermovelezosorio,hospitalgeneraldevalladolid).
hospital(luisoliveriocardenasmoreno,hospitalgeneraldelacdmx).
hospital(mariaisabellopezgaviria,hospitalgeneraldelacdmx).
hospital(mariavictoriaariasgomez,imss).
hospital(oscardariogomezgiraldo,hospitalgeneraldevalladolid).
hospital(oscardariomurillogonzalez,hospitalgeneraldevalladolid).
hospital(sixtonaranjomarin,imss).
hospital(williamdejramirezvasquez,hospitalgeneraldelacdmx).

%estados en los que se encuentran los hospitales

estado(hospitalgeneraldelacdmx,mexico).
estado(hospitalgeneraldevalladolid,yucatan).
estado(hospitalgeneraldechampoton,campeche).
estado(hospitalgeneraldecancun,quintanaroo).
estado(imss,yucatan).
estado(institutonacionaldeenfermedadesrespiratorias,monterrey).

%ciudades en donde se encuentran situados los hospitales

ciudad(yucatan,valladolid).
ciudad(quintanaroo,cancun).
ciudad(mexico,cdmx).
ciudad(nuevoleon,monterrey).
ciudad(campeche,champoton).
