%lista de pacientes ingresados al sistema

paciente(adolfoleoncorreasilva).
paciente(alejandroalzategarces).
paciente(alfredotobontobon).
paciente(alvarodejesusbocanumenthpuerta).
paciente(alvarodejesussaldarriagavasquez).
paciente(alvaroivanberdugolopez).
paciente(angelgabrielarrublaortiz).
paciente(armidbenjaminmunozramirez).
paciente(arturotabaresmora).
paciente(augustoosornogil).
paciente(beatrizelenaosoriolaverde).
paciente(beatrizelenapuertabolivar).
paciente(bernardoposadavera).
paciente(carlosalbertovillegaslopera).
paciente(carlosalbertozarateyepez).
paciente(carlosaugustogiraldo).
paciente(carlosmariomontoyaserna).
paciente(cesaroswaldopalaciomartinez).
paciente(octaviodiazperez).
paciente(fabioalexanderflorezgarcia).
paciente(gabrieljaimejimenezgomez).
paciente(gerardoemilioduquegutierrez).
paciente(germanantonioloteroupegui).
paciente(gloriaamparoalzateagudelo).
paciente(gloriaelenasanclementezea).
paciente(gonzalolopezgaviria).
paciente(gustavohernanrodriguezvallejo).
paciente(hectordamianmosquerabenitez).
paciente(hectordariobermudezsaldarriaga).
paciente(hectorivangonzalezcastaño).
paciente(hectormanuelpineda).
paciente(hermancorrearamirez).
paciente(hernandariohurtadoperez).
paciente(horacioaugustomorenocorrea).
paciente(jaimelopeztobon).
paciente(javierignacioaguilargomez).
paciente(javierignaciomolinacano).
paciente(jhonyalbertosaenzhurtado).
paciente(johnjairoduquegarcia).
paciente(jorgeleonruizruiz).
paciente(jorgeuribebotero).
paciente(josedidierzapatasuarez).
paciente(juliocesarrodasmonsalve).
paciente(juliocesarrodriguezmonsalve).
paciente(lidapatriciagiraldomorales).
paciente(lillianeugeniagomezalvarez).
paciente(luisalfonsoescobartrujillo).
paciente(luisanibalsepulvedavillada).
paciente(luisfernandocastrohernandez).
paciente(luisguillermovelezosorio).
paciente(luisoliveriocardenasmoreno).
paciente(mariaisabellopezgaviria).
paciente(mariavictoriaariasgomez).
paciente(oscardariogomezgiraldo).
paciente(oscardariomurillogonzalez).
paciente(sixtonaranjomarin).
paciente(williamderamirezvasquez).