%estados actuales de los pacientes registrados

status(adolfoleoncorreasilva,cuarentena).
status(alejandroalzategarces,muerto).
status(alfredotobontobon,recuperacion).
status(alvarodejesusbocanumenthpuerta,recuperado).
status(alvarodejesussaldarriagavasquez,muerto).
status(alvaroivanberdugolopez,recuperacion).
status(angelgabrielarrublaortiz,recuperado).
status(armidbenjaminmunozramirez,recuperado).
status(arturotabaresmora,muerto).
status(augustoosornogil,cuarentena).
status(beatrizelenaosoriolaverde,cuarentena).
status(beatrizelenapuertabolivar,cuarentena).
status(bernardoposadavera,muerto).
status(carlosalbertovillegaslopera,recuperacion).
status(carlosalbertozarateyepez,recuperacion).
status(carlosaugustogiraldo,recuperado).
status(carlosmariomontoyaserna,recuperado).
status(cesaroswaldopalaciomartinez,cuarentena).
status(octaviodiazperez,recuperado).
status(fabioalexanderflorezgarcia,muerto).
status(gabrieljaimejimenezgomez,recuperacion).
status(gerardoemilioduquegutierrez,recuperado).
status(germanantonioloteroupegui,recuperado).
status(gloriaamparoalzateagudelo,cuarentena).
status(gloriaelenasanclementezea,cuarentena).
status(gonzalolopezgaviria,cuarentena).
status(gustavohernanrodriguezvallejo,muerto).
status(hectordamianmosquerabenitez,muerto).
status(hectordariobermudezsaldarriaga,muerto).
status(hectorivangonzalez,muerto).
status(hectormanuelpineda,recuperacion).
status(hermancorrearamirez,cuarentena).
status(hernandariohurtadoperez,cuarentena).
status(horacioaugustomorenocorrea,cuarentena).
status(jaimelopeztobon,muerto).
status(javierignacioaguilargomez,cuarentena).
status(javierignaciomolinacano,recuperado).
status(jhonyalbertosaenzhurtado,recuperado).
status(johnjairoduquegarcia,cuarentena).
status(jorgeleonruizruiz,muerto).
status(jorgeuribebotero,recuperacion).
status(josedidierzapatasuarez,recuperado).
status(juliocesarrodasmonsalve,muerto).
status(juliocesarrodriguezmonsalve,recuperacion).
status(lidapatriciagiraldomorales,muerto).
status(lillianeugeniagomezalvarez,recuperado).
status(luisalfonsoescobartrujillo,cuarentena).
status(luisanibalsepulvedavillada,cuarentena).
status(luisfernandocastrohernandez,cuarentena).
status(luisguillermovelezosorio,cuarentena).
status(luisoliveriocardenasmoreno,muerto).
status(mariaisabellopezgaviria,recuperado).
status(mariavictoriaariasgomez,muerto).
status(oscardariogomezgiraldo,muerto).
status(oscardariomurillogonzalez,recuperado).
status(sixtonaranjomarin,recuperacion).
status(williamderamirezvasquez,recuperacion).